name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows-nightly:
    runs-on: windows-latest

    steps:
      - name: checkout xingapi
        uses: actions/checkout@v2

      - name: checkout xingapi-sdk (windows branch)
        uses: actions/checkout@v2
        with:
          repository: konan8205/xingapi-sdk
          ref: windows
          ssh-key: ${{ secrets.SDK_TOKEN }}
          path: ./xingapi-sdk/windows
          clean: false

      - name: checkout xingapi-sdk (res branch)
        uses: actions/checkout@v2
        with:
          repository: konan8205/xingapi-sdk
          ref: res
          ssh-key: ${{ secrets.SDK_TOKEN }}
          path: ./xingapi-sdk/res
          clean: false

      - run: mkdir -p C:/eBEST/xingAPI
        shell: bash

      - run: cp -r ./xingapi-sdk/windows/* C:/eBEST/xingAPI
        shell: bash

      - run: cp -r ./xingapi-sdk/res/* C:/eBEST/xingAPI
        shell: bash

      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: i686-pc-windows-msvc
          override: true

      - name: build xingapi
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --target i686-pc-windows-msvc
            --workspace
            --tests
            --all-features

      - name: test xingapi
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: |
            --target i686-pc-windows-msvc
            --workspace
            --all-features
            --
            --test-threads 1
